name: Call Validate PR

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited

jobs:
  validate-pr:
    uses: entur/tmp-gh-workflows-2/.github/workflows/pr-validation.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
