name: publish

on:
  push:
    branches: [master]

jobs:
  create-release:
    runs-on: ubuntu-latest
    needs: tf-docs
    steps:
      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # - name: Conventional Changelog Action
      #   id: changelog
      #   uses: TriPSs/conventional-changelog-action@9b8c94a880e647cdc3e5071e15e20f0fe210b5ce # v3.13.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     output-file: "false"
      #     version-file: "version.yaml"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{needs.tf-docs.outputs.version}}
          release_name: ${{needs.tf-docs.outputs.version}}
          body: ${{needs.tf-docs.outputs.changelog}}
