name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    uses: entur/gha-meta/.github/workflows/release.yml@v1
    with:
      release_type: "terraform-module"
